config/routes.rb
BookWriter::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'books#index'

  devise_for :users

  get 'books/:book_id/chunks/:id/versions/show' => 'versions#show'
  post 'books/:book_id/chunks/:id/versions/:current_id/revert/:old_version_id' => 'versions#revert_to_old_version'

  resources :books do
    get 'print', :on => :member
    post 'close', :on => :member
    get 'new_edition', :on => :member
    resources :chunks, :except => [:index] do

      resources :versions,:except =>[:index] do
        post 'compare', :on => :member
        get 'version', :except => [:index]
      end
    end
  end

end

app/models/version.rb
class Version < ActiveRecord::Base
  attr_accessible :id, :item_id, :item_type, :whodunnit, :object, :created_at

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def show
    @content_size = 100                                              #Obergrenze für Contentgröße in übersicht
    @chunk = Chunk.find(params[:chunk_id])                           #Chunk aus DB laden
    @book = Book.find(@chunk.book_id)                                #Buch aus DB laden
    if params[:entries].to_i > 0                                     #Wenn Übersichtseinträge größer null sind, dann nur gewählte Anzahl anzeigen
      @entries = [params[:entries].to_i,@chunk.versions.size].min    #wenn weniger Versionen als anzuzeigende Einträge vorhanden sind
    else
      @entries = @chunk.versions.size                                #sonst alle Versionen zeigen
    end
    unless params[:entries]                                          #wenn anzahl von einträgen nicht vorhanden ist (erster aufruf der seite)
      @entries = [10,@chunk.versions.size].min                       #standardmäßig auf 10 setzen oder nur so viele wie es Versionen gibt
    end
  end

  def revert_to_old_version                                          #Methode zum zurücksetzen der Version
    #@chunk.versions(params[:old_version_id]).reify.save!
    @chunk = Chunk.find(params[:id])                                 #Chunk aus DB laden
    @chunk.versions[params[:old_version_id].to_i].reify.save!        #Version aus versions-hash laden und als Aktuelle in DB speichern
    redirect_to  edit_book_chunk_path                                #Weiterleitung zum bearbeiten des neuen Chunks
  end

  def version                                                        #Methode zum Zeigen der Version
    @book = Book.find(params[:book_id])
    @chunk = Chunk.find(params[:chunk_id])
    @version = ''                                                    #@Version initialisieren
    if (! params[:version_id] == 0 )                                 #Prüft ob es sich um den aktuellen Chunk oder eine Version handelt
      @version = Version.find(params[:version_id]).reify.content     #Version
    else
      @version = Chunk.find(params[:chunk_id]).content               #Chunk
    end

  end

  def compare
    @book = Book.find(params[:book_id])                              #Book aus DB laden
    @choice = {}                                                     #Array für ausgewählte Versionen
    i = 0
    params.each do |p|                                               #Params durchsuchen nach keys, die mit 'vers' beginen
      if p[0][0..3].eql?('vers')                                     #wenn 'vers'-key gefunden wurde
        @choice[i] = p[1]                                            #speichern des zugehörigen values
        i = i + 1
      end
    end

    @chunk = Chunk.find(params[:chunk_id])                           #Chunk laden
    if (@choice[0] == '0')                                           #Wenn version1==parameter, dann
      @version1 = Chunk.find(params[:chunk_id]).content              #aktuelle Version laden
    else                                                             #sonst
      @version1 = @chunk.versions[@choice[0].to_i].reify.content     #die gewählte version laden
    end
    if (@choice[1] == '0')                                           #analog zu Version2
      @version2 = Chunk.find(params[:chunk_id]).content
    else
      @version2 = @chunk.versions[@choice[1].to_i].reify.content
    end
  end

end

app/views/versions/compare.html.erb
<h1>Versionsvergleich</h1>

<table class="table table-striped max700">
  <tr>
    <th>version1</th>
    <th>version2</th>
  </tr>

  <tr>
     <td><%= v1 = raw(@version1) %></td>
     <td><%= v2 = raw(@version2) %></td>
  </tr>

</table>

<%= button_to 'Zurück', :back, method: :get, :class => 'btn btn-default backbutton' %>

app/views/versions/show.html.erb
<%= stylesheet_link_tag "versions" %>

<h2>Versionsübersicht: <%= @book.title %> / <%= @chunk.title %></h2>

<%= form_tag(compare_book_chunk_version_path, method: :post) do %>
<table class="table table-striped">
  <tr>
    <th></th>
    <th>Version</th>
    <th>Inhalt</th>
    <th>Benutzer</th>
    <th>Erstellt am</th>
    <th></th>
    <th></th>
  </tr>

  <tr>
    <td>
      <%= check_box_tag 'vers' + 0.to_s, '0', false, {:onclick => 'setChoice(%s)' % 0} %>
    </td>
    <td>Aktuell</td>
    <td>
      <%= raw(@chunk.content[0..@content_size]) %>
    </td>
    <td><%= User.find(@chunk.user_id).username %></td>
    <td><%= @chunk.created_at.strftime("%d.%m.%Y %H:%M:%S")  %></td>
    <td></td>
    <td><%= button_to 'hallo','', :style => 'display:none' %>
      <%= button_to 'Ansehen',book_chunk_version_version_path(@book,@chunk,0), method: :get,:class => 'btn btn-default btn-xs'  %></td>
  </tr>

  <% @entries.times do |i| vers = @chunk.versions[@chunk.versions.last.index - i]%>
    <% unless vers.index == 0 %>
      <tr>
        <td>
          <%= check_box_tag 'vers' + vers.index.to_s, vers.index, false, {:onclick => 'setChoice(%s)' % vers.index} %>
        </td>
        <td><%= vers.index %></td>
        <td><%= raw (vers.reify.content[0..@content_size]) %></td>
        <td><%= User.find(vers.whodunnit).username %></td>
        <td><%= vers.created_at.strftime("%d.%m.%Y %H:%M:%S")  %></td>
        <td><%= button_to 'Zurücksetzen', @chunk.book_id.to_s << @chunk.id.to_s << '/revert/' << vers.index.to_s , method: :post,:class => 'btn btn-default btn-xs' %></td>
        <td><%= button_to 'Ansehen',book_chunk_version_version_path(@book,@chunk,vers.id), method: :get,:class => 'btn btn-default btn-xs'  %></td>
      </tr>
      <% end %>
  <% end %>
  <tr>
    <td colspan="7">
      <div id="selectEntryAmount">
        <%=link_to '10', {:controller => 'versions', :action => 'show', :entries => '10'}%> |
        <%=link_to '25', {:controller => 'versions', :action => 'show', :entries => '25'}%> |
        <%=link_to '50', {:controller => 'versions', :action => 'show', :entries => '50'}%> |
        <%=link_to 'All', {:controller => 'versions', :action => 'show', :entries => '-1'}%>
      </div>
    </td>
  </tr>

</table>
    <div class="submitbutton">
        <%= submit_tag 'Vergleichen' ,:id => 'compare', :disabled => 'true', :class => 'btn btn-default'%>
    </div>
<% end %>

<%= button_to 'Zurück', book_url(@chunk.book_id) , method: :get, :class => 'btn btn-default backbutton'%>

app/views/versions/version.html.erb
<h1>Version</h1>

<div class="version">
  <%= raw(@version) %>
</div>

<%= button_to 'Zurück', :back, method: :get, :class => 'btn btn-default backbutton' %>